### PR TITLE
RA| updated enketo to use geo location

### PR DESCRIPTION
**Pull request by raihan-mpower**

### CODE REVIEW

**Comment by raihan-mpower** [comment]
@koros @dimasciput can you review this

**Comment by koros** [comment]
@raihan-mpower thanks for the update, unfortunately at the moment i can't load any forms i always get this error on the logs:
07-30 15:30:17.644  14634-14634/org.ei.opensrp E/DRISHTI? Javascript Log. Message: Uncaught TypeError: Object [object Object] has no method 'getForm'file:///android_asset/www/enketo/js/enketo-dristhi-combined.min.js405, lineNumber: 405, sourceId, file:///android_asset/www/enketo/js/enketo-dristhi-combined.min.js
but thats not related to your changes, its been there for a while now, i am trying to establish at the moment the exact revision.
is anyone else experiencing this issue? @dimasciput ?

**Comment by raihan-mpower** [comment]
i have the same error....surprisingly this does not occur in my mcare fork....i am on it....will try to resolve it asap

**Comment by raihan-mpower** [comment]
@koros and @dimasciput  can you recheck the latest commit on this branch to see if the error is still there....i am not getting the error anymore but one of the 4 devices i have is not loading the form , i need to know if its only exclusive to that particular device . Emulator and genymotion is also loading the forms without errors

**Comment by dimasciput** [comment]
@raihan-mpower : I'll check on it.

**Comment by dimasciput** [comment]
@raihan-mpower : I've fixed it in this pull request : https://github.com/OpenSRP/opensrp-client/pull/74

**Comment by raihan-mpower** [comment]
@dimasciput  thanks i have pulled the #74 with my branch and now it works in all devices.......can you review this branch and merge

**Comment by koros** [comment]
@raihan-mpower thanks for the update it looks good on my end, i am no longer having any issues. @dimasciput can review if everything is working fine

**Comment by raihan-mpower** [comment]
actucally @dimasciput  is the one who fixed the issue with jsAnnotations.

**Pull request merged**
