### PR TITLE
Issue19

### PR DESCRIPTION
**Pull request by dimasciput**
Create UI for location dropdown modal

### CODE REVIEW

**Comment by dimasciput** [comment]
> #19

**Comment by dimasciput** [comment]
@raihan-mpower , already tested the new location implementation, works fine.

**Comment by dimasciput** [comment]
One thing left to do is wrap the library.

**Comment by raihan-mpower** [comment]
@dimasciput  we can not wrap the library as it uses some style file and layout files , which when made into jar file are not getting references to the layout files, also we would have to wait on the merge part as the user "demotest" needs to have location structure similar to the one drishti had so that the locations could be pushed to the forms from the selector using form override json and not use hardcoded into the form definitions , for ex the way villages are selected in the ec_registration form.

**Pull request merged**
