### PR TITLE
Issue17

### PR DESCRIPTION
**Pull request by dimasciput**
Auto downloading form

### CODE REVIEW

**Comment by ndisha** [comment]
@dimasciput please rebase this with master - this branch cant be automatically merged to master..

@raihan-mpower please review this code - @dimasciput was waiting for your review.

**Comment by raihan-mpower** [comment]
@dimasciput can you resolve the conflicts , also it seems you have worked on the context file, in my other pull request in #27  i have also worked on the context file too, could we have that merged to master and then pulled to this branch and fix the conflicts?

**Comment by dimasciput** [comment]
@raihan-mpower You need to review this branch first and then I can solve the conflicts when merging into master. Conflicts is usually happened.

**Comment by raihan-mpower** [comment]
Error:(117, 39) java: cannot find symbol
  symbol:   variable FORM_DOWNLOAD_URL
  location: class org.ei.drishti.AllConstants
Error:(56, 44) java: cannot find symbol
  symbol:   variable ALL_FORM_VERSION_URL
  location: class org.ei.drishti.AllConstants

There is something wrong with the constants...have you pushed your changes in allconstant?

**Comment by dimasciput** [comment]
Oops, forgot to push that one. Sorry.

**Comment by raihan-mpower** [comment]
this seems fine functionally,i tested it, so it will use the 'download/opensrp' folder it its there or else the assets if available;that is okay. 
In #27 issue15clean pull request i changed the initRepository() method and how repositories were being sent to the Repository constructor. Could you kindly see that and probably adjust for formsVersionRepository there.
Can you fix the conflicts and then i can check it again.

**Comment by dimasciput** [comment]
@raihan-mpower , Hi Raihan, I think we could do that when we merging your branch. We want to merge my branch first right? So we can resolving the conflicts of the repository while we merging yours. What do you think?

**Comment by raihan-mpower** [comment]
i think its better to merge #27 first as it changes initRepository , and since you would know better where you are adding the repository and which ones....its safer.....
we can merge #issue15clean and then #25 . I will try and clean up the commonobject sort as you suggested.

**Comment by dimasciput** [comment]
@raihan-mpower , I will try to merge this one by myself and resolve the conflicts.

**Pull request merged**
