### PR TITLE
Thrivepk branch for merge to master

### PR DESCRIPTION
**Pull request by maimoonak**
#295 Addressing issue of core merging of vaccinator app to master

### CODE REVIEW

**Comment by raihan-mpower** [comment]
this is a huge pull request , my initial observation is that there are lot of changes like css and resource change stuff done in core library . It would be great if @keymane or @maina could look at it and also if you could achieve that by overriding the resources of the library in your module instead of opensrp-client module . For references maybe you can look into these links (i am sure there are way better articles on overriding resources/resource merging or resource referencing between libraries and project modules):
https://developer.android.com/studio/write/add-resources.html
http://tools.android.com/tech-docs/new-build-system/resource-merging

**Comment by maimoonak** [comment]
Documentation would be here https://smartregister.atlassian.net/wiki/display/Documentation/Thrivepk+as+client+core

**Comment by maimoonak** [comment]
Thanks @raihan-mpower . This is helpful. I should have overridden the enkteo css and js in project. Other resources have been deleted and modified intentionally. I would explain it in detail in call this week.

**Comment by raihan-mpower** [comment]
https://github.com/OpenSRP/opensrp-client/pull/296/commits/7c135c4a4eba959c229df58ab1d577a22267c8ff
this would require us to change a lot of code , infact declare all columns in bindtypes.json file and also in all of our codes in across all three apps. If you want to use this you can extend commonRepository and override the methods (Probably name it ColumnedCommonRepository). Then use the extended one in your registers. That way it would probably not break the current structure. Else this is going to create a lot of problems in all our apps if we were to merge this with the master.

**Comment by maimoonak** [comment]
As discused in call and considering the fact that the merge is going to
make other sites do a lot of refactor in their code, and since everyone hav
tight timelines, we have decided (after discussion with Ona team) to change
code in our module. This would not add any conflicting code and merge would
be automatic. Rightnow we are using master repo as a base and making
changes to our module. Hopefully no one else is making changes to core code
...

**Comment by maimoonak** [comment]
Not applicable

**Pull request closed without merging**
