### PR TITLE
Spike on modularisation

### PR DESCRIPTION
**Pull request by gigix**
Moved child register to its own folder to show how to modularise a register. Now you need specify a implementation site as profile when you run maven build, like this:

<code>mvn clean install -Pbangladesh</code>

### CODE REVIEW

**Comment by ndisha** [comment]
can you please review and merge this.

**Comment by maimoonak** [comment]
##### Urgent and  Important!!!
@gigix : Were you able to build and run the app with this. On windows, it did not allow me to build without making changes to dependency versions and skipping tests. It happens across different OS, so just wanted to confirm if it works as it is for your OS.

@gigix , @raihan-mpower , @dimasciput , @mberg , @djazayeri 
Below are the problems and concerns you need to provide input on.. Also please make sure to decide the approach asap since it may affect the client code in longer run.

##### Problems with merge
- The branch contains code just for child register and for merging code inside main repo it should be in a consistent and usable state. i.e. All registers should be converted to follow the structure that Jeff has proposed
- @raihan-mpower has made alot of changes into the code and his work is NOT following this structure. Merging code with main repo may make Raihan`s work done till today unmergeable and go wasted
- The code here follows org.ei.drishti package and Raihan has renamed all everything.
- I don`t know the details but I think Raihan was working on making ALL code controlled by central activities and controllers. His approach is opposite to what Jeff has done i.e. moved all register specific code to separate folder with self contained repo, activities, views, controllers etc. We need to get consensus on what architecture we are going to follow in longer run.
- If we go with Jeff`s approach, someone has to first convert complete project on this structure and then rename packages to org.opensrp again. Also if there had been any refactoring in client by any dev it has to be either done again or merged carefully to remove all conflicts in code.

**Comment by mberg** [comment]
Maimoona -  agree thanks for catching this.  I'll email raihan now and we
will try and discuss this on Monday before things proceed further.

**Comment by raihan-mpower** [comment]
this still has issues with running karma test while doing a maven build. Apart from that it works fine.
I think i can wait for this to be merged to the main branch and then rename the packages.
The other work i did regarding simplifying the registers is compatible with this branch

**Comment by maimoonak** [comment]
@raihan-mpower On windows I was able to run and build it with maven-karma-plugin version 1.6 and setting skip tests properties true in maven. However, I did not try running app so not sure if it could be installed on mobile

**Comment by ndisha** [comment]
@dimasciput @raihan-mpower in view of the renaming the packages being the last thing on our commit plan, do we want to have this merged before we rename? Let me know what you decided on this,

**Pull request closed without merging**
