### PR TITLE
Adding settings to login screen

### PR DESCRIPTION
**Pull request by raihan-mpower**
@ahmedihs  can you review this , i have created a new pull request , this is the same as #44

### CODE REVIEW

**Comment by ahmedihs** [comment]
@raihan-mpower  everything looks fine. i have question that you are going to add settings to login or should i ???

**Comment by ahmedihs** [comment]
i have one suggestion/question that we still load setting from sharedpreferences , after loading it from app.properties  . if user changes the url in sharedpreference by that way , it could connect to new server url .

**Comment by raihan-mpower** [comment]
@ahmedihs  i have already added this to login activity ........
https://github.com/OpenSRP/opensrp-client/commit/c8ae47ca3c9fe9459101b3804e4fcfd57a774683
we are loading setting from sharedpreferences, just the deafault is taken from app.propeteties in case it gets no values.

**Comment by ahmedihs** [comment]
there is no menu option shown in loginactivity .

**Pull request merged**
