### PR TITLE
Replace xpath evaluator

### PR DESCRIPTION
**Pull request by koros**

### CODE REVIEW

**Comment by koros** [comment]
DO NOT MERGE: don't merge this yet the form overrides aren't working

**Comment by koros** [comment]
The issue is now resolved, @maimoonak you can merge the changes to your branch to perform benchmark test

**Comment by koros** [comment]
@raihan-mpower please review this again, i had left out the workaround we had put in place to refresh the date fields if a user uses back key to dismiss the date picker dialog.

**Comment by koros** [comment]
@raihan-mpower please resolve this soon so that i can create a pull request for Issue##207 since its based on this.

**Comment by raihan-mpower** [comment]
@koros i checked this, function wise form is working as before, but since i checked and compared in genymotion the speed seemed same even after the xpath evaluator addition.
This seems to be forked from an old branch, i worked on the css of the forms to make the questions larger , will this change that after merging? can you do a pull from master and check this?
screenshot from 2016-05-15 20 49 48
this is how the forms look after css change which are different from this branch

**Comment by koros** [comment]
@raihan-mpower The css wont change since the new js/css dependencies folder was re-created a fresh, you can modify the css as before.
The performance improvement for the Bangladesh forms would be subtle, since there isn't a lot of complex logic but nonetheless the fields should be more responsive now, e.g typing in the 13/17 digit NID should be faster.

**Comment by raihan-mpower** [comment]
@koros can you pull the master and merge into this branch and check for conflicts before i merge the pull request?

**Comment by koros** [comment]
@raihan-mpower i have updated the branch please confirm whether everything is fine now

**Pull request merged**
