### PR TITLE
Issue3

### PR DESCRIPTION
**Pull request by raihan-mpower**
Changed package names from org.ei.drishti to org.ei.opensrp

### CODE REVIEW

**Comment by dimasciput** [comment]
@raihan-mpower , there are still error in the test. See below 

```
Failed tests:
  ECClientTest.ShouldReturn1YearsWhenDOBIs18_4_2013:70 expected:<1> but was:<2>
  ECClientTest.shouldReturn0YearsWhenDOBIs4_4_2014:61 expected:<0> but was:<1>
  ECClientTest.shouldReturn34YearsWhenDOBIs4_4_1980:52 expected:<34> but was:<35>
  ECClientTest.shouldSatisfyFilterForNameStartingWithSameCharacters:91 null
Tests in error:
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeECSmartRegisterActivityTest.setup:43 » Reflection Unable to invoke metho...
  NativeHomeActivityTest.setup:23 » Reflection Unable to invoke method 'performC...
  NativeHomeActivityTest.setup:23 » Reflection Unable to invoke method 'performC...
  NativeHomeActivityTest.setup:23 » Reflection Unable to invoke method 'performC...
  NativeHomeActivityTest.setup:23 » Reflection Unable to invoke method 'performC...
  NativeHomeActivityTest.setup:23 » Reflection Unable to invoke method 'performC...
  NativeHomeActivityTest.setup:23 » Reflection Unable to invoke method 'performC...
  NativeHomeActivityTest.setup:23 » Reflection Unable to invoke method 'performC...
```

**Comment by raihan-mpower** [comment]
@dimasciput  can you try and see even if the master has same errors in tests? i am getting the same errors in master too

**Comment by dimasciput** [comment]
@raihan-mpower I only get this error :
```
Failed tests:
  ECClientTest.ShouldReturn1YearsWhenDOBIs18_4_2013:70 expected:<1> but was:<2>
  ECClientTest.shouldReturn0YearsWhenDOBIs4_4_2014:61 expected:<0> but was:<1>
  ECClientTest.shouldReturn34YearsWhenDOBIs4_4_1980:52 expected:<34> but was:<35>
```

**Comment by raihan-mpower** [comment]
that is strange , i am getting these errors in most branches..........

**Comment by dimasciput** [comment]
@raihan-mpower , what error? the ECClientTest one or NativeECSmartRegisterActivityTest? 
I only get the ECClientTest error, and I think the error is from the old dristhi.

**Comment by raihan-mpower** [comment]
I am getting errors in both NativeECSmartRegisterActivityTest and ECClientTest

**Comment by dimasciput** [comment]
Well that's weird, I don't get NativeECSmartRegisterActivityTest error. Did
you test it on the master branch too?

On Tue, Apr 21, 2015 at 4:44 PM, raihan-mpower <notifications@github.com>
wrote:

> I am getting errors in both NativeECSmartRegisterActivityTest and
> ECClientTest
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSRP/opensrp-client/pull/28#issuecomment-94704906>.
>



-- 
Regards,
Dimas Tri Ciputra

**Comment by raihan-mpower** [comment]
yes i have tested on master too....which is weird....i even tried out in other branches

**Comment by raihan-mpower** [comment]
@dimasciput I have fixed it... can you please check now..:)

**Comment by dimasciput** [comment]
Okay, it's fixed. :+1:

**Pull request merged**
