### PR TITLE
Ci setup

### PR DESCRIPTION
**Pull request by koros**
Completed setting up CI environment for client;
Currently most of the existing tests are failing so we should move to fix them soon. in the meantime the build script is just making sure the committed code doesn't break build.

### CODE REVIEW

**Comment by dimasciput** [comment]
@koros , ok can we merge this now? Or should we wait after fixing all the tests?

**Comment by koros** [comment]
@dimasciput we can merge it now as it is, then once we fix the tests we enable tests executions, its still useful now as it is since it ensures the code compiles e.g the developer hasn't inadvertently forgotten to commit a resource or file etc.

**Comment by dimasciput** [comment]
@koros , yes I agree, thanks. I will merge it now.

**Comment by koros** [comment]
@dimasciput cool, thanks.

**Pull request merged**
