### PR TITLE
Put error handler in activity and fragment class

### PR DESCRIPTION
**Pull request by johansid**
I added this error handle at fragment and activity class

### CODE REVIEW

**Comment by dimasciput** [comment]
@johansid what is .EAP files? Why did you push it?

**Comment by johansid** [comment]
Hi Dimas,
Thanks for your attention.
I was wrong to put reverse engineering file to my work folder.
Just ignore it.

-----Original Message-----

**Comment by dimasciput** [comment]
@johansid you're welcome. Anyway you can't just ignore it, if you don't want to push these files you have to remove it.
Just remove it on your branch, and push the changes.

**Comment by johansid** [comment]
@dimasciput it is my first time using this github, i will delete
Thanks for @kercobo give me training for this stuff.
About system.exit(2)
I put this on create to give android clear message about malfunction because system internal android dosnt hve spesific error message.
System.exit(2) mean there is mal function on local class.
CMIIW yaa...

**Pull request closed without merging**
