### PR TITLE
Issue86

### PR DESCRIPTION
**Pull request by raihan-mpower**
added image repository and methods to sync image captured in device to server.
@dimasciput @koros can you review this pull request.
thanks

### CODE REVIEW

**Comment by dimasciput** [comment]
Is the server ready for this?

**Comment by dimasciput** [comment]
@raihan-mpower

**Comment by raihan-mpower** [comment]
@julkarnain @maimoonak can answer this

**Comment by maimoonak** [comment]
I can see Multimedia related classes in master server repo. I guess @julkarnain tested it working and sending data

**Pull request merged**
