### PR TITLE
Pk vaccinator faster forms

### PR DESCRIPTION
**Pull request by koros**
This branch contains latest version of the opensrp-indonesia-faster-forms and pk_vaccinator_faster_forms so @kercobo and @ahmedihs please confirm that the code is still intact before we merge to master. Thanks.

### CODE REVIEW

**Comment by ahmedihs** [comment]
@koros  code isnot intact . please dont merge it now

**Comment by koros** [comment]
@ahmedihs alright, what issue have you noticed

**Comment by kercobo** [comment]
@koros  looks good to me.

**Comment by koros** [comment]
@kercobo alright cool, thanks. @ahmedihs what issue did you find?

**Comment by koros** [comment]
@MohammadSafwan @kercobo @raihan-mpower i intend to merge in this one today unless a serious issue is reported, if we delay any longer the PR will get out of sync with master then we'll have to restart the whole process once again.
My suggestion we perform the merge, then open separate tickets to fix any known issues
Known issue currently:
- [ ] Travis build fail (Will resolve this later since it may involve some changes in the project structure/dependencies)

**Comment by MohammadSafwan** [comment]
I pulled the code and then tested it. The form is being saved now with the gps. The app wasn't crashing at any point though but some bugs have occurred:

- The existing data has stopped coming.
- Isn't uploading the data i.e. is not syncing. Can't find the data on the server too.

**Comment by koros** [comment]
Hi @MohammadSafwan from our last discussion i had understood that there are some issues but you are fixing them, so i knew you are working on resolving some of these issues, but, you can do a quick check, checkout your last commit 07f38409cebf00d71b8ec1a55daa4d64231a4a16 and compare that to the merged branch

**Comment by koros** [comment]
Merged pk_vaccinator_faster_forms @MohammadSafwan create issue branch to resolve the issues that are still pending.

**Comment by koros** [comment]
@MohammadSafwan also let me know if there is anything that isn't working as expected

**Pull request merged**
