### PR TITLE
Issue2

### PR DESCRIPTION
**Pull request by raihan-mpower**
#2 addressed here .

### CODE REVIEW

**Comment by dimasciput** [comment]
@raihan-mpower , I successfully open the ec form, but there is not geopoint picker. Did you added geopoint picker in that form? Or am I missing something here?

**Comment by raihan-mpower** [comment]
the current dristhi forms do not have geo point picker......I can give a sample form with geo point picker if you need....what we we need to figure is if this is working fine when forms are being submitted.

**Comment by dimasciput** [comment]
Can you give me the example of the form that using this? So I can test it.

On Sat, Apr 18, 2015 at 4:19 AM, raihan-mpower <notifications@github.com>
wrote:

> the current dristhi forms do not have geo point picker......I can give a
> sample form with geo point picker if you need....what we we need to figure
> is if this is working fine when forms are being submitted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSRP/opensrp-client/pull/26#issuecomment-94066494>.
>



-- 
Regards,
Dimas Tri Ciputra

**Comment by raihan-mpower** [comment]
i mailed you a sample form

**Comment by dimasciput** [comment]
It gives me this error when I click the picker. I'm using Genymotion emulator. 

**ERROR: SQLite database failed to load from /GeolocationPermissions.db**

**Comment by raihan-mpower** [comment]
can u try on a different emulator or in device.....i think the emulator is having problems with giving the app geolocation persmissions

**Comment by dimasciput** [comment]
Is it gonna be problem? Because not all devices will be working. But yeah,
I'll try it on the device.

On Tue, Apr 21, 2015 at 1:29 PM, raihan-mpower <notifications@github.com>
wrote:

> can u try on a different emulator or in device.....i think the emulator is
> having problems with giving the app geolocation persmissions
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSRP/opensrp-client/pull/26#issuecomment-94642497>.
>



-- 
Regards,
Dimas Tri Ciputra

**Comment by raihan-mpower** [comment]
no it wont be...if a device does not have gps , people should not have forms with gps recording in them

**Comment by ndisha** [comment]
@dimasciput @raihan-mpower - this pull request been here for a while; its now not possible to merge it, can we review the conflicts and merge it?

**Comment by raihan-mpower** [comment]
@ndisha  ok i am on it

**Comment by ndisha** [comment]
Hey @raihan-mpower @dimasciput just fagging this one out as having stayed for too long..

**Comment by ndisha** [comment]
Functionality handled by this PR: https://github.com/OpenSRP/opensrp-client/pull/72, closing this!

**Pull request closed without merging**
