### PR TITLE
Issue212

### PR DESCRIPTION
**Pull request by raihan-mpower**
recent UI changes and pageination page number fix. This is a combination of fix of several issues.

### CODE REVIEW

**Comment by maina** [comment]
@raihan-mpower   "Is there any specific reason that mauza name is all caps? I think if it's not all caps, you'd be able to see more of the name in the Profile column before it gets cut off", Any response to this?
Also in "ANC Details" screen, History section, the last item value is always in bold which shouldn't be the case..

**Comment by raihan-mpower** [comment]
@maina the caps is because the names come from the location tree in all caps and we had discussion regarding the location names , the reason we cants have the cells large enough as some of the titles of other cells would go supressed and also the users can see the name of the location in the details anyways

**Comment by cagulas** [comment]
@raihan-mpower so the names from the location tree come from OpenMRS location module, right? So Numera or someone would have to edit the location names in the location module on OpenMRS, correct? If she did this, would this affect any existing data?

**Comment by raihan-mpower** [comment]
if would affect existing data as current data has locations in caps , the newer ones would have location in lower cases

**Comment by cagulas** [comment]
right, ok, but I'm asking is whether it would break anything? Maybe it's not worth the trouble then, what do you think?

**Comment by raihan-mpower** [comment]
yea it would break existing sort and search. We shortened the birth notification title, so maybe will get some space. Also reducing to lower case would not save much space anyways.

**Comment by cagulas** [comment]
Ok, fair enough.

**Pull request merged**
