### PR TITLE
Issue39

### PR DESCRIPTION
**Pull request by raihan-mpower**
RA| added filter for common registry object controller, we can give p…arameters in case we need to filter the objects we retrieve from database via parameters in the constructor

### CODE REVIEW

**Comment by raihan-mpower** [comment]
@dimasciput can you review this

**Comment by dimasciput** [comment]
Hi @raihan-mpower , would you please make a test case for this? It would be very helpful.

**Comment by raihan-mpower** [comment]
ok sure will do

**Comment by raihan-mpower** [comment]
@dimasciput  i have added the test case for the filters in the controller

**Comment by dimasciput** [comment]
I think it's fine, I will merge it

**Pull request merged**
