### PR TITLE
Preference feature

### PR DESCRIPTION
**Pull request by mahmedyousuf**
Notes :

File : HttpAgent : line 130
Method - setCredentials 
changes : changing data from configuration.host() and REALM to null 
Reason : if host is not set to null , the app doesnt allow to user to login . show Messages"  Crenditials are wrong" 

File : AllSharedPreferences  
Method : fetchBaseURL , FetchHOST, FetchPort .
Change : adding  all these methods to class , to get data from sharedpreferences.
reason : this class is global sharedpreferences for all the app.

File : DristhiConfiguration 
Method : dristhiBaseURL(),host()  ,port() 
Change : changing return values , getting data now from sharedpreferences
reason : all connectivity data now comes from sharedpreferences

File : SettingActivity + preference.xml
Change : adding these files for preference view .

### CODE REVIEW

**Comment by ahmedihs** [comment]
@raihan-mpower  now you can adding option for preference in app

**Comment by raihan-mpower** [comment]
@ahmedihs can you work on the branch in this repo instead of your fork of opensrp client and also i would like to make some changes . I would recommend taking data from the app.properties file unless a commit has been made in settings activity that way we do not entirely replace the previous system. Secondly 
preferences.getString(DRISHTI_BASE_URL,"localhost"); in AllSharedPreferences might give localhost in case it doesn't find the DRISHTI_BASE_URL, i am guessing there might be atleast one sharedpreference.commit before this happens , so i am not sure....i need to test it out......so can you please close this pull request and create a new one from the branch in this repo , i created a branch in this repo and pulled your changes , the branch name is the same. I will make some changes you can review them.

**Comment by raihan-mpower** [comment]
ok i made some minor changes apart from that the code is pretty much the same and it works fine.....thanks ....i have added it on option selected in login activity and also i have replaced the deprecated method addPreferencesFromResource(R.xml.preferences) with preference fragment.......i am closing this pull request and creating a new one with the branch from this repo.....i will tag you in it ....you can review and provide a feedback......

**Comment by ahmedihs** [comment]
basically there is a commit before ,it loads default data specified in preferenceActivity , it is where it first loads data .

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#65

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#75

**Pull request closed without merging**
